version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-blueocean
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

